### PR TITLE
Update phenomic to 0.20.1 (latest)

### PR DESCRIPTION
**Pull request by meuwka**
Fix for #230 
I suggest to update phenomic to fix the issue

### CODE REVIEW

**Comment by marcustisater** [comment]
Awesome, thank you so much for the update. LGTM

@thangngoc89 do mind looking through as well?

**Comment by thangngoc89** [comment]
This LGTM. Btw, phenomic is under a rebuild from ground-up so this kind of update process will be stopped forever. :D

**Comment by marcustisater** [comment]
yeah, we will wait for major release next time

**Comment by ai** [comment]
@marcustisater when you will deploy it? 😊

**Comment by ai** [comment]
I am really worry that @meuwka did not in production yet 😟

**Comment by marcustisater** [comment]
It should be live https://github.com/postcss/postcss.org/tree/gh-pages but maybe it's appcache that is causing this...? @MoOx any ideas..?

**Comment by ai** [comment]
@marcustisater I am sure, that it is not appcache, because Chrome Incognito Tab (it works without any caches) sees old version.

**Comment by thangngoc89** [comment]
Something went wrong with the deployment process, your gh-page branch wasnt updated since 6 months ago.

**Comment by marcustisater** [comment]
That's wired... I will look into it. Sorry!

**Comment by marcustisater** [comment]
any ideas why that's so @thangngoc89?

**Comment by marcustisater** [comment]
I heard you can setup auto deployment with Netlify, then I can solve #211 as well. I will look into it right away.

**Pull request merged**
