### PR TITLE
Add Google Analytics

### LINKED ISSUE #166: Add Google Analytics
I create a Google Analytics account. Here is a tracker code:

```
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-73693753-1', 'auto');
  ga('send', 'pageview');

</script>
```

/cc @marcustisater

### PR DESCRIPTION
**Pull request by halvves**
Should close #166 

Let me know if this has been implemented correctly.

### CODE REVIEW

**Comment by mxstbr** [comment]
@MoOx I haven't worked with this component before – does this look alright?

**Comment by MoOx** [comment]
Seems to work for me.

screen shot 2016-02-12 at 22 53 18

**Comment by mxstbr** [comment]
@MoOx I mean, does @halvves implementation look correct? :wink: I'm sure it works generally!

**Comment by MoOx** [comment]
Yeah, lgtm.

**Comment by MoOx** [comment]
@halvves did you easily find how to introduce the UA value? (I want statinamic to be very easy to setup, please report any bad DX to me ^^).

**Comment by halvves** [comment]
@MoOx - it was very straight ahead. thanks! i appreciate how concerned you are with dx.

**Pull request merged**
