### PR TITLE
Converted .com to .org

### PR DESCRIPTION
**Pull request by marcustisater**
We are moving to .org #50

### CODE REVIEW

**Comment by mxstbr** [comment]
LGTM

**Comment by ai** [comment]
LGTM

**Comment by ai** [comment]
@mxstbr so only one “LGTM” is needed?

**Comment by mxstbr** [comment]
Yeah, we just changed it as a trial. See https://github.com/postcss/postcss.org/pull/52#issuecomment-171421623

**Comment by mxstbr** [comment]
It's not necessary to wait for a second reviewer for PRs like this one, one person looking over it should be fine.

**Pull request merged**
