### PR TITLE
Added dependencies to Gulp and restrucutre directory with correct mockup

### PR DESCRIPTION
**Pull request by marcustisater**
@stephenway - What do you think?

### CODE REVIEW

**Comment by stephenway** [comment]
Looks good, but your merge will conflict with the README Mockup section that was just added. You will need to rebase on master first.

**Comment by marcustisater** [comment]
I think you also can solve directly in the gui - this should have fixed it tho.

**Comment by stephenway** [comment]
LGTM

**Comment by marcustisater** [comment]
You are not set in the [maintainers](https://github.com/postcss/postcss.org/blob/master/MAINTAINERS) list, let me add you.

**Pull request merged**
