### PR TITLE
Adds auto deploy for gh-pages

### PR DESCRIPTION
**Pull request by marcustisater**
Is this the correct setup for auto deployment with phenomic script? @thangngoc89 

Thanks!

### CODE REVIEW

**Comment by marcustisater** [comment]
We used to do auto deploy with Travis but I'm not sure why that is not working...

**Comment by thangngoc89** [comment]
If you copy-pasted this from phenomic's docs, it's pretty much it. You also need to actually run the deployment (after build process)

**Comment by thangngoc89** [comment]
Looks like you forgot the token 
See https://phenomic.io/docs/usage/gh-pages/#copy-and-encrypt-this-new-token

**Comment by marcustisater** [comment]
thanks

**Comment by bdougie** [comment]
Netlify does this and also adds the ability to [preview](https://www.netlify.com/blog/2016/07/20/introducing-deploy-previews-in-netlify/) changes through GitHub's CI as well. @marcustisater, did you try out the [open source](ttps://www.netlify.com/open-source/) plan and were there any hang ups there?

**Comment by marcustisater** [comment]
unfortunately yes... read more #211

**Comment by marcustisater** [comment]
Besides that I love Netlify, great overview and easy to setup. Unfortunately we prefer the domain without the www prefix.

**Comment by biilmann** [comment]
Hi Marcus,

Netlify founder and big PostCSS fan here (we use it in all our sites and apps)!

You can use postcss.com on Netlify as well - we expose a public IP for that usecase
in our docs https://www.netlify.com/docs/custom-domains/#dns-configuration

The recommendation about using www instead of postcss.com is not specific to Netlify, it's
just how DNS works. So as long as you're using a DNS provider that doesn't have some form
of CNAME flattening or ANAME records, your site will be significantly slower on the naked
domain than it could be on the www domain. It's actually one of the reasons that we offer
our own integrated DNS solution as part of Netlify, so we can offer naked domains without
any performance compromises.

However, using the naked domain with Netlify, won't be any different than your current setup,
and will let you setup HTTPS and use deploy previews, etc...

GitHub pages also recommends using a www domain for the same reasons:

https://help.github.com/articles/about-supported-custom-domains/#www-subdomains

Obviously postcss would be a great fit for our free open-source plan :)

Cheers,
Matt

**Comment by marcustisater** [comment]
Hello Mathias,

Thank you for reaching out! I spoke to Chris earlier about this (great support). Our boss in charge @ai has a very strong opinion on the www prefix, we will make sure to get in touch once we have talked it over within the team.

**Comment by ai** [comment]
@biilmann hi. It is so good to hear that you are fans of PostCSS :).

We really want to implement HTTPS too. But using `www.` is not a option (for some political problem, I was big enemy of it). Maybe there is a way to use your awesome service without having `www.` prefix?

**Comment by thangngoc89** [comment]
Hey @ai @marcustisater i think @biilmann pointed out clearly, if you dont want www prefix, you can create an A record that point to 104.198.14.52 instead of a CNAME. It's normal DNS configuration

**Comment by ai** [comment]
@thangngoc89 great! @marcustisater do you have access to do it?

So I am right now on Sri Lanka with friends a lot alcohol :D

**Comment by marcustisater** [comment]
lol :joy: but I think our DNS provider today it's not possible?

**Comment by ai** [comment]
@marcustisater so, current problem is only because we have no `A` record for main domain? If it so, I could try to find it.

**Pull request closed without merging**
