### PR TITLE
Added some markup changes

### PR DESCRIPTION
**Pull request by marcustisater**
Just free crafting some markup changes so the Hero component wouldn't get wrapped in. 

I have to admit, very new to React and best practices when it comes to semantic html, so please review... 

Don't merge, maybe you can clean up and work from this otherwise just throw! :smile:

### CODE REVIEW

**Comment by marcustisater** [comment]
btw it complains if I don't define any styles within the component when I import an stylesheet. Any work-arounds that I'm missing?

**Comment by MoOx** [comment]
lgtm. FYI, incoming version of will have an "assets" folder. Will be handy for some images (eg: evil martian logo?)

**Comment by marcustisater** [comment]
Yeah, that would be awesome @MoOx

**Comment by mxstbr** [comment]
Travis fails because of the Gulpfile linting errors - should be fine if I merge though, right?

**Comment by marcustisater** [comment]
postcss.org/web_modules/Wrapper/index.js
`8:8  error  "styles" is defined but never used  no-unused-vars`

`npm test` is also not running correctly, it searches through the entire node_modules dir

**Comment by MoOx** [comment]
Are you on windows?

**Comment by marcustisater** [comment]
No, OS X El Capitan.

**Comment by MoOx** [comment]
I don't see what is happening.

**Comment by marcustisater** [comment]
Ok, I found the problem. I had node_modules inside the `design` directory that was not ignored...

**Comment by MoOx** [comment]
it's in the gitignore, that's weird.

**Comment by marcustisater** [comment]
Yeah but don't you have to specify an absoulte path for it?

**Comment by marcustisater** [comment]
anyway, I think we need to consider on what's going to be lint and what not, would we do gulp babel for example? Maybe just lint the web_modules dir?

**Comment by MoOx** [comment]
For gitignore no, but maybe eslint can't handle it the same way http://eslint.org/docs/user-guide/configuring#ignoring-files-and-directories
Imo you should lint every single .js that are versionned.

**Comment by marcustisater** [comment]
Ok make sense. Humm yeah it's probably eslint that's picking it up either way.

**Comment by marcustisater** [comment]
I will take a look at the linter #131

**Pull request merged**
