### PR TITLE
Initial development setup

### PR DESCRIPTION
**Pull request by mxstbr**
I'm not sure which design to follow, since the one from Zeplin is different from the one in the design folder which is different from the one in the issue. @marcustisater 

This is some basic markup setup with a few classes and structure.

### CODE REVIEW

**Comment by mxstbr** [comment]
Don't merge this yet!

**Comment by mxstbr** [comment]
Review please! @marcustisater

**Comment by marcustisater** [comment]
The one output as PNG in the repository is wrong - it has to be updated. I'm confused as well. 

Latest:
https://cloud.githubusercontent.com/assets/11071/12518954/03429518-c13c-11e5-9df3-86582a60604f.png

I will talk to stephen and okonet asap.

**Comment by marcustisater** [comment]
code

LGTM

**Comment by stephenway** [comment]
Need @okonet to update the sketch file in the repo, then we can update Zeplin

**Comment by marcustisater** [comment]
should resolve some major concerns 

https://github.com/postcss/postcss.org/pull/114

**Pull request merged**
