### PR TITLE
Add OpenGraph image

### LINKED ISSUE #162: Social meta tags
We need better OpenGraph and other social media tags. At least we need a tag with image for OpenGraph tag.

### PR DESCRIPTION
**Pull request by okonet**
Closes #162

### CODE REVIEW

**Comment by marcustisater** [comment]
What compression technique did you use for the image?

**Comment by okonet** [comment]
Progressive JPEG with 40% q in Sketch.

**Comment by marcustisater** [comment]
Alright, we can look into how can we reduce it later on. I still think it's too big.

**Comment by marcustisater** [comment]
LGTM

**Comment by marcustisater** [comment]
make sure to pull next time hehe

**Comment by okonet** [comment]
😱

**Comment by marcustisater** [comment]
Is it ok for me to merge https://github.com/postcss/postcss.org/pull/165 ? It fixes some stuff, I'll convert px to rems this weekend.

**Comment by okonet** [comment]
Sure. Go ahead

**Pull request merged**
