### PR TITLE
Add Gitter button

### PR DESCRIPTION
**Pull request by meuwka**
Add code from https://sidecar.gitter.im/ through `react-helmet`

### CODE REVIEW

**Comment by ai** [comment]
@meuwka should we set `async` and `defer` to `true`?

**Comment by ai** [comment]
@meuwka Travis CI reported about `SyntaxError: Unexpected token .`. Do you have it locally? Or it is problem in tests?

**Comment by ai** [comment]
Other tricky question. Should we change default color of this button?

@meuwka how it looks right now? Is it green as in official docs? Is it hard to change it to brand red (`#dd3a0a`)? 

@marcustisater do you think that brand red will be the best for this button?

**Comment by meuwka** [comment]
@ai Hi! Travis CI reported this issue in master also. Problem is in `highlight.js` file
I'm not sure about `defer` (old browsers) but 'async' probably we should use because script is embedding in `<head >` I set `undefined` value because it's way from docs `react-helmet` (when attribute takes no value)
Yea, button is green, we can create our own button. Sidecar has `activationElement` in options

**Comment by ai** [comment]
Great :). I think we could merge even green version of it.

Let’s wait for @marcustisater review. I think it could take few hours. So if you have time you could make button red in current PR :).

**Comment by ai** [comment]
@meuwka great! Thanks for you work :).

@marcustisater ping me when you deploy it :)

**Comment by meuwka** [comment]
@ai thanks :)

**Comment by marcustisater** [comment]
You are correct, the error is from `highlight.js` and not from this PR. I will create separate issue for that.

This PR LGTM, good work @meuwka 🎉😄

**Comment by marcustisater** [comment]
@ai It's live now but appcache so it might take a while 😅

**Pull request merged**
