### PR TITLE
Added some styles to footer [touch:103]

### PR DESCRIPTION
**Pull request by marcustisater**
just some styles, I had to fix linter problem in the Wrapper component.

btw, did we agree on any specific css architecture @mxstbr - any suggestions?

### CODE REVIEW

**Comment by mxstbr** [comment]
What do you mean with CSS Architecture? We're using CSS Modules...

**Comment by mxstbr** [comment]
LGTM

Sorry for not working on this website at all, have been really busy. Will start soon!

**Comment by marcustisater** [comment]
I am so stupid, sorry. Every class is generated unique, first time using CSS Modules. It's so nice to finally be able to forget all about BEM etc :smile: 

but any specifications towards declaring classnames in the js file?

**Comment by mxstbr** [comment]
Nope, the way you did it was perfect, though I'd probably give `.info a` it's own classname too. :+1:

**Comment by marcustisater** [comment]
Alright, thank you very much! 

> Sorry for not working on this website at all, have been really busy. Will start soon!

No worries, pick it up when you have time for it. There is no deadline or pressure, everyone should have fun a long the way and learn something new! :)

**Comment by marcustisater** [comment]
You are correct, it should have a class name. I will fix that.

**Pull request merged**
