### PR TITLE
Add .editorconfig

### PR DESCRIPTION
**Pull request by ai**
Will be useful for new developers to config text editor.

@marcustisater are this `.editorconfig` is correct?

### CODE REVIEW

**Comment by marcustisater** [comment]
Good idea, I think the config is good.

lgtm

**Comment by marcustisater** [comment]
I would like a second opinion before merging this:

@MoOx - What do you think?

**Comment by okonet** [comment]
Here is my config: 

```
root = true

[*]
indent_style = space
indent_size = 4
continuation_indent_size = 4
end_of_line = lf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true

[*.js]
quote_type = single
spaces_around_operators = true

[*.{scss,css}]
quote_type = double
indent_size = 4

[*.{html,json}]
quote_type = double

[*.md]
trim_trailing_whitespace = false

[*.json]
indent_size = 2
```

as an example.

**Comment by ai** [comment]
At least `Footer/index.js` has 2 space indent.

**Comment by ai** [comment]
Also we can add according ESLint

```
[*.js]
quote_type = double
```

**Comment by MoOx** [comment]
This little config lgtm 👌.

**Comment by marcustisater** [comment]
hehe, figured if you wanted to add something that you have? ;)

**Comment by MoOx** [comment]
I use a very similar config https://github.com/MoOx/statinamic/blob/master/.editorconfig

**Pull request merged**
