### PR TITLE
Fix link to postcss/brand repository

### PR DESCRIPTION
**Pull request by awayken**

### CODE REVIEW

**Comment by marcustisater** [comment]
Thank you Miles for submitting you're very first pull request to [postcss.org](http://postcss.org) :tada: 

Great catch with correcting a broken link at the [docs](https://github.com/postcss/postcss.org/tree/master/docs), let me know if there is anything I can help you with to get started with or making contributing easier for you.

**Comment by marcustisater** [comment]
LGTM

**Comment by awayken** [comment]
Thanks, @marcustisater. I'm a big fan of PostCSS and its community, and I hope I can find more ways to contribute.

**Comment by marcustisater** [comment]
Absolutely, you are very welcome to do so.

We are doing some organizing but [Milestone 1.1](https://github.com/postcss/postcss.org/milestones/1.1) is the best way to start of with if you want to hack on some code or discussion threads. 

Don't be afraid to ask any questions or for assistance.

**Pull request merged**
