### PR TITLE
Code highlight

### PR DESCRIPTION
**Pull request by okonet**
I've added code highlighting for CSS snippets.

Also updated snippet's styles a bit to better match the mockup.

### CODE REVIEW

**Comment by marcustisater** [comment]
I will take a look tonight, can you quickly look into https://github.com/postcss/postcss.org/pull/152

**Comment by okonet** [comment]
I realize we could parse the code during the generation. This will only require the CSS file with highlight.js theme to be included. But I think I might need some assistance with Statinamic

**Comment by marcustisater** [comment]
That looks nice, I like the highlighting of the code. Is anything with the changes you made failing? I think we should add this right away once #153 is closed or what help do you need with Statinamic?

**Comment by okonet** [comment]
We could add it as is. My thought was is that might be too much JS for the front-page and simple examples and it looks like Statinamic has an ability to render Markdown with syntax highlighting. But we could do that later as well. So let's merge and add an issue? @MoOx?

**Comment by MoOx** [comment]
Like you said, you can do it with markdown or js. You decide :)

**Comment by okonet** [comment]
i think it might be too much JS deps just for the home page. @MoOx how can I try "server" rendering out? Will every `*.md` file processed so I can just extract the examples?

**Comment by MoOx** [comment]
I am not following what you asked.
Every .md files are processed via markdown-it and currently, highlight.js is used to enhance code snippets between 3 backticks (like on github markdown).
You can just throw some code in an md file and you will get hightlight.js html classes for the code.

**Comment by MoOx** [comment]
See https://github.com/postcss/postcss.org/blob/6c7ef51b67e0636a5c75f10435d7f971d3fd3908/scripts/build.js#L119-L127

**Comment by okonet** [comment]
That's exactly what I asked. Thanks. I'll try to do it on "server".

**Comment by MoOx** [comment]
During the build step* :)
Currently .md are transformed to json that contains some html, but that might changes in the future (but you don't care about that, usage and result will be the same as today).

**Comment by okonet** [comment]
@MoOx so how do I render the result in React? What I get from requiring the `*.md` file is a path to a JSON file.

**Comment by MoOx** [comment]
Don't do anything. [That's the magic part of Statinamic](https://github.com/postcss/postcss.org/blob/master/scripts/index-client.js#L2).
You can just throw some md in ``content/index.md`` and access it like this in your Homepage component: https://github.com/postcss/postcss.org/blob/2115f7d041292e9998a8f63011c259d050ec2e73/web_modules/layouts/Page/index.js#L56-L58

**Comment by MoOx** [comment]
Otherwise (if you don't want or cannot rely on this index.md file), you currently cannot really can require a md file (you will need some async fetched code) the what the current codebase is made.
Another solution (if you don't have a lot of code is to just render some code with highlight js and grab the rendered html "by hand" (not very maintainable, I admit).

**Comment by okonet** [comment]
Sorry I don't understand how it works. Can you update my PR or let's merge it as is.

**Comment by MoOx** [comment]
Don't have time for this atm. Sorry. tl;dr: merge as it is imo :)

**Comment by marcustisater** [comment]
I think it's ok to throw JS in there for now, we can optimize it later with markdown files. We only have one page for now :)

**Comment by marcustisater** [comment]
LGTM

**Pull request merged**
