### PR TITLE
Static html

### PR DESCRIPTION
**Pull request by ai**
- [x] Replace React to static HTML
- [x] Replace webpack to Parcel for better DX
- [x] Add CSS/JS inlining to improve performance
- [x] Add Size Limit
- [x] Fix header image quality problem
- [x] Fix a11y issues
- [x] Replace two fonts to the one font for better performance
- [x] Increase font size a little for better readability
- [x] Add deploy on commit to `master`
- [x] Remove Google Analytics for better performance and user’s privacy

## Results

* **360 → 20** ms for Max Potential First Input Delay
* **3.3 → 1.5** seconds for First CPU Idle
* **3.3 → 1.5** seconds for Time to Interactive
* **68 → 27** requests
* **511 → 312** KB to transfer
* 100% in Lighthouse for Performance, Accessibility, and Best Practices.

### CODE REVIEW

**Comment by ai** [comment]
@okonet are you OK with a font number reducing? Now Fire Sans only to improve performance.

**Comment by ai** [comment]
@marcustisater do we right now deploy to GitHub Pages or to Netlify?

**Comment by okonet** [comment]
Looking good!

**Comment by marcustisater** [comment]
WOW! Nice job @ai 😍

I love the performance results. 

You decide if we use GitHub Pages or Netlify. Netlify gave us free plan to use. It will auto trigger the deploy on push to `master` branch. It runs `npm run build` and publish `dist` dir. Should I change build steps to anything else?

**Comment by ai** [comment]
@marcustisater what do we use right now? Netlify is nice, but have problem with banning in Russian. But right now [postcss.org is not banned](https://isitblockedinrussia.com/?host=postcss.org).

**Comment by marcustisater** [comment]
@ai ok, interesting. Yes, we use Netlify today. Domain is pointed to Netlifys DNS.

**Comment by marcustisater** [comment]
@ai if you want I can look into https://docs.netlify.com/domains-https/netlify-dns/#ipv6-traffic

**Comment by ai** [comment]
In this case let's continue to use Netlify.

I will update PR (and add the config for better caching).

**Comment by marcustisater** [comment]
Great, let me know when you are ready and if I need to change any build configs in Netlify 🥳

**Comment by ai** [comment]
@marcustisater can you add me to Netlify? Or set `NODE_ENV=production` in `Settings > Build & deploy > Environment > Environment variables`?

Netlify build is not working in the PR because Netlify refuse to call `yarn install --production`.

**Comment by marcustisater** [comment]
I invited andrey@sitnik.ru to Netlify. Changed NODE_ENV but it didn't help. I will help you debug.

**Comment by marcustisater** [comment]
I see you found out why it's not working. We are using gh-paes 😂 🙈

**Comment by marcustisater** [comment]
@ai did gh-pages auto deploy? I am so sorry I confused things...

**Comment by ai** [comment]
I made an auto-deploy via Travis CI

**Comment by ai** [comment]
I think we need to delete Netlify project to avoid confusion is the future :)

**Comment by marcustisater** [comment]
I just deleted it. Great with auto deploy. I think it's also good idea to remove LGTM. I will delete old branches too. 

Thanks for cleaning things up 😅

**Pull request merged**
