### PR TITLE
HomePage

### PR DESCRIPTION
**Pull request by jeddy3**
I figured I’d get the ball rolling with this one. It was quite difficult to work on the individual components at this stage of the build as I needed to create a coherent CSS system across them all. Therefore, this PR is for all the `HomePage` components. Going forward though, the components can be evolved individually as they are all standalone.

The main caveat is that I took numerous liberties to speed up the development, these include:

* Using _System UI_ fonts.
* Using one font size for each element across all viewport sizes.
* Only adapting _the layout_ as the viewport size increase, and keeping adaptations to an absolute minimum.
* Using a baseline grid of 8px. Font sizes and line heights are set in pixels to easily facilitate this.
* Using a spacing system of factors of 8px, e.g. 4px, 8px, 16px, 24px etc, to compliment this baseline. These map onto easy-to-use fractions of `rem` units e.g. `8px` = `0.5rem` and `16px` = `1rem`.
* Using a very basic universal selector reset rather than `initial: all`.
* Using webpack’s `file-loader` to include assets.
* Constructing the `HomePage` from simple dumb and static components.
* Not using the `Button` component within the `HomePage`.
* Not implementing a burger menu. Although, this is [arguably](https://lmjabreu.com/post/why-and-how-to-avoid-hamburger-menus/) a good thing for UX.
* Breaking the `NavBar` apart into `Navigation` and `Social`.
* Not implementing a carousel for the items in the “In a nutshell” section when viewed in a narrow viewport. Again though, [arguably](http://www.creativebloq.com/accessibility-expert-warns-stop-using-carousels-7133778) this is a good thing for UX.
* The examples in the “In a nutshell” section do not break out of their containers.
* Not adding the github star button to the `Hero`.

The good news:

* It’s mobile first i.e. built to work on the smallest screen and the fattest figures first, then enhanced (but only where absolutely necessary).
* It’s “content-out” i.e. each component adapts according the layout requirements of it’s own content.
* It’s tested in latest Chrome (Mac + Android), Safari, Firefox and IE.
* The “In a nutshell” section got a bit hairy, but I persevered as it’s a key section and I think those blue highlights within the examples do an excellent job of quickly illustrating the features of each tool.
* I’ve tried to keep the CSS architecture as consistent as possible e.g. `compose:` is only used for variants/modifiers and nesting is used only for pseudo classes and elements.

A took the liberty of adding `stylelint` back into the “In a nutshell” section. It had disappeared between mock-up versions, but I couldn’t find any discussion to why. I added little labels to the examples within the “In a nutshell” section to distinguish between CSS output and console output

I couldn’t find what the big blue button navigation component should be called… so I named it `WayFinder`.

I began merging together the styleguide and the `web_modules`, but finishing this is task for another time. It is functional at the moment though.

A copy of the build is available to view at:
http://dev.richardhallows.com/

Building a whole website is a huge undertaking. I suggest soft launching something like this and then iterating on it. For example, optimisations might come next… or building the sub pages from the markdown docs in the main repo. I’m hopefully this PR will provide a solid foundation to build from.

Once this PR is reviewed and merged, I can make a little more time to document the conventions I’ve used. Which we hopefully make it a tad easier for another developer to pick things up.

### CODE REVIEW

**Comment by mxstbr** [comment]
Reviewing, one sec.

**Comment by mxstbr** [comment]
LGTM

Amazing work @jeddy3, thanks so much!

**Comment by marcustisater** [comment]
Wow, christmas did really come early, the list you made really makes sense and I agree with you having an minor launch, will talk with Audrey about it. It would be great with documentation as you said, that's the key of helping developers to pick this up. 

Amazing work @jeddy3, we can't thank you enough for the work you have put into this and creating issues. 

Btw, what happened to the deploy script @mxstbr ?

**Comment by marcustisater** [comment]
Ah nvm I remember, it's automatic deployment with travis. It's up live now.

**Comment by jeddy3** [comment]
>  It would be great with documentation as you said, that's the key of helping developers to pick this up.

I'll make time for it :) 

Is there any chance you can add me as a contributor to the repo? I find local Pull Requests a little easier to manage than ones from forks.

**Comment by marcustisater** [comment]
Absolutely, I will add you right away.

**Pull request merged**
