### PR TITLE
Added a few font-sizes adjustments

### PR DESCRIPTION
**Pull request by marcustisater**
some font-sizes changes and colors for tagline

### CODE REVIEW

**Comment by marcustisater** [comment]
@okonet maybe we need to overlook the mobile font sizes as well?

**Comment by okonet** [comment]
Why aren't we using relative font sizes and adjust just in one place depending on media query? We use `rem` but `px` for font sizes. This doesn't feel right to me. Same applies to `line-height`. I never use values in `line-height` BTW.

**Comment by marcustisater** [comment]
Yup, makes sense. I followed from what was done but we can remake it. I'm on it.

**Comment by marcustisater** [comment]
Let me close this one and remerge new branch.

**Comment by marcustisater** [comment]
but wait @okonet is it ok if we merge this one in? It solves some issues for now until we can remake it in relative font-sizes.

**Pull request merged**
