### PR TITLE
Contribute

### PR DESCRIPTION
**Pull request by marcustisater**
Added REAMDE file for contributing content to postcss.org

### CODE REVIEW

**Comment by marcustisater** [comment]
#73

**Comment by mxstbr** [comment]
LGTM

**Comment by mxstbr** [comment]
I don't understand why LGTM doesn't pass. Any ideas?

**Comment by marcustisater** [comment]
**approvals/lgtm — Waiting for status to be reported**

That is wired.

**Comment by marcustisater** [comment]
LGTM

**Comment by mxstbr** [comment]
One second, I think I might've fixed the problem - somebody switched it off entirely.

**Comment by mxstbr** [comment]
There we go: All checks have passed

**Comment by marcustisater** [comment]
Great :+1:

**Pull request merged**
